### PR TITLE
Fix Measure import on README example

### PR DESCRIPTION
**Pull request by gabrielsch**
Just spent an hour figuring it out 😅

### CODE REVIEW

**Comment by souporserious** [comment]
Oh no! Sorry about that 😓 I'm working on a [new version](https://github.com/souporserious/react-measure/tree/rewrite) right now. Is it installing the `rc` version by default? I'll add something to the README and update the rewrite README with respective changes to the new version.

**Comment by jfurfaro** [comment]
@souporserious yes, looks like the `rc` version is default for npm right now

**Comment by GlebDolzhikov** [comment]
Yes pls notify user some how that docs written for 2.0.2 version, in current npm version Measure don't work well, even if it named imported. contentRect property don't bring anything.. spend 2 hour on it!

**Comment by jfurfaro** [comment]
Yes, even installing `react-measure@2.0.2` was creating broken builds for some reason - and i had been using that version for months without issue, no code changed. But deleting the `node_modules/react-measure` folder and reinstalling the same version gave me issues.

**Comment by souporserious** [comment]
Ah dang that sounds bad 😕 sorry about that! I'm not entirely sure what to do 😩. I updated the README. Does anyone know of a way to point default installs to a different version in NPM?

**Pull request closed without merging**
