### PR TITLE
add what measurements are available in readme

### PR DESCRIPTION
**Pull request by chrisdrackett**

### CODE REVIEW

**Comment by souporserious** [comment]
Thanks! Can we add that only width and height are observed? Top, right, bottom, and left are given as a convenience.

**Comment by chrisdrackett** [comment]
So i just wrote this code, are you saying this is basically the default behavior?

```jsx
<Measure whitelist={['width', 'height']}>
```

**Comment by souporserious** [comment]
Yeah. I never mentioned it 😞 which has lead to issues [like this](https://github.com/souporserious/react-measure/issues/39).

**Comment by chrisdrackett** [comment]
ok, updated. I'm guessing that in an ideal world you would also be able to watch the other props?

**Comment by souporserious** [comment]
Thanks! That works for now :) yeah I think I'm going to create two components that check for dimensions and position separately.

**Pull request merged**
