### PR TITLE
Upgrade babel to beta

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by souporserious** [comment]
Looks like there's a small conflict from the other PR. Curious why this isn't a dev dependency? 🤔 Sorry, I haven't been following the latest Babel releases 😇.

**Comment by TrySound** [comment]
Done.

**Comment by souporserious** [comment]
Thanks! What's the purpose of that living in `dependencies`? Does it add to the final bundle at all?

**Comment by TrySound** [comment]
babel runtime is dependency injected by babel by transform-runtime. It contains helpers and polyfills.

**Comment by TrySound** [comment]
It does not necessary add something, but what is added will be reused across packages.

**Comment by souporserious** [comment]
Sounds good, thanks!

**Pull request merged**
