### PR TITLE
Updated to React 16

### PR DESCRIPTION
**Pull request by hkelly93**
Removed createElement to allow use with React 16.

### CODE REVIEW

**Comment by TrySound** [comment]
@hkelly93 And how createElement does not work with react? To what babel transpiles jsx?

**Comment by hkelly93** [comment]
I changed what was suggested and it worked in my code.

**Comment by TrySound** [comment]
What did not work?

**Comment by TrySound** [comment]
Suggested by whom?

**Comment by hkelly93** [comment]
In the bug that was opened, let me close the PR and we can discuss it there.

**Pull request closed without merging**
