### PR TITLE
Fix not passing ResizeObserver entries to measure method, closes #124

### LINKED ISSUE #124: ResizeObserver entries are undefined when measure method is called
This was introduced with https://github.com/souporserious/react-measure/commit/446e3e8281b86a0e81438424ca39ca121ad7418f 
as `measure` method is missing the entires from ResizeObserver callback 

```js
_resizeObserver = new ResizeObserver(() => {
  this.measure()
})
```

### PR DESCRIPTION
**Pull request by piecyk**
@souporserious maybe something like this ?

### CODE REVIEW

**Comment by souporserious** [comment]
Oh geez 🤦‍♂️ I messed that one up. Thank you for submitting a PR! Could this be a little simpler and just pass entries to the `measure` method? Something like:

```js
_resizeObserver = new ResizeObserver(entries => {
  this.measure(entries)
})
```

**Comment by piecyk** [comment]
Yeah it will work, my proposal adds small micro optimization, null checks and set the ResizeObserver when component mounted.  

As note to your initial commit https://github.com/souporserious/react-measure/commit/446e3e8281b86a0e81438424ca39ca121ad7418f with fix callback error... IMHO there is no need for na extra arrow function... The `measure` method is class properties that's way you need the extra wrapper as is would be used before it's initialization, or at least how i see it 🤔

**Comment by piecyk** [comment]
Basic if you want to create the ResizeObserver instance on initialization without wrapper, need to move it to constructor 

```js
// ...
_animationFrameID = null

_resizeObserver = null

_node = null

constructor(props) {
  super(props)
  this._resizeObserver = new ResizeObserver(this.measure)
}

componentWillUnmount() {
// ...
```

**Comment by souporserious** [comment]
@piecyk that totally makes sense. Thanks for the explanation! I’m going to merge this and then should have a new release tomorrow. Sorry for the delay, I’ve been on vacation this last week 😇.

**Comment by souporserious** [comment]
Released under `v2.2.3` 🎉. Thank you for your contributions! 🙏

**Comment by piecyk** [comment]
Awesome 👏 Thanks @souporserious 🙌

**Pull request merged**
