### PR TITLE
New API to make measuring multiple elements easier RFC

### PR DESCRIPTION
**Pull request by souporserious**
After working with the old API for a few years it always seemed to work well for single element use cases, but then started to fall apart the more elements that needed to be measured. This is the main driver of this rewrite and the goal is for ease of use, while providing the best performance possible.

### Measure

With this rewrite we remove `measureRef` and `contentRect ` in place of `bind` and `measurements` in the `Measure` component.

####  `bind`

Responsible for subscribing elements to a `ResizeObserver` and keeping track of element size changes.

####  `measurements`

Returns `null` before first measure, and returns all measured children on subsequent renders.

#### Measure Example

Let's see how we can measure a list of items with the new API:

```jsx
import React from 'react'
import { Measure } from 'react-measure'

function App({ items }) {
  return (
    <Measure>
      {({ bind, measurements }) =>
        items.map((item, index) =>
          <div {...bind(index)}>
            <pre>
              {measurements && JSON.stringify(measurements[index], null, 2)}
            </pre>
          </div>
        )
      }
    </Measure>
  )
}
```

#### Viewport

We also introduce a new component called `Viewport`. This is responsible for providing current viewport scroll positions and dimensions.

#### Viewport Example

```jsx
import React from 'react'
import { Viewport } from 'react-measure'

function App({ items }) {
  return (
    <Viewport>
      {({
          width,
          height,
          scrollWidth,
          scrollHeight,
          scrollX,
          scrollY,
          scrollXDirection,
          scrollYDirection
      }) =>
        <div>
          Do things with viewport dimensions and scroll positions :)
        </div>
      }
    </Viewport>
  )
}
```

## Install

`yarn add react-measure@latest`

`npm install react-measure@latest --save`

The current release candidate is in a production app powering auto size calculations for tables and collapse components so it's been working great so far, but I'd love to hear thoughts on these API changes and whether there can be improvements or more features. I'll work on new documentation and even further explanations above once I get a chance 😅 

My goal is to get the following examples all working so we know it can work in multiple, and sometimes complex use cases:

- [x] Table
- [x] Collapse
- [ ] Carousel
- [ ] Flip
- [ ] Grid
- [ ] OverflowMenu
- [ ] Popover
- [ ] [ScrollAnimations](http://gilbox.github.io/react-track/examples/demo/demo.html)
- [ ] [ScrollyTelling](https://kubrick.life/spartacus1/)
- [ ] StickySidebar
- [ ] Tabs
- [ ] AutoSizer/[ParentSize](https://github.com/hshoff/vx/tree/master/packages/vx-responsive#parentsize)
- [ ] [Scroll Indicator](https://codepen.io/vaibhavarora/pen/NMxbwE?editors=0010)
- [ ] [Hierarchical Animation](https://codepen.io/devlee/pen/qqPPjE?editors=0010)
- [ ] [Chat Window](http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html)

### CODE REVIEW

**Comment by TrySound** [comment]
viewport example is uncolored

**Comment by souporserious** [comment]
Yeah haha sorry 😅 crappy pass on docs right now. Going to get some sleep, but I'll explain things better and clean everything up tomorrow.

**Comment by TrySound** [comment]
You don't wanna see Dan's talk about new react features?

**Comment by souporserious** [comment]
Oh yeah! Haha maybe I'll just nap for a few hours 😛

**Comment by jedwards1211** [comment]
I feel slightly wary of the way `bind` is written, as if it might inject additional props in the future.  If it injected listeners someday, they might accidentally catch bubbling listeners from children.  Also, it becomes more awkward to wrap the `ref` created by `bind` in the case that you need to observe an element's size *and* keep a ref to it for other purposes.

**Comment by jedwards1211** [comment]
Somehow this comment doesn't seem to have posted: I think `watch` or `observe` or `follow` would be a better name for that function than `bind`, because `bind` is a vague word that usually means something totally different in JS programming.

**Comment by TrySound** [comment]
@jedwards1211 `bind` means you bind some functionality to element. Here we don't need to have concrete word. You may just don't use destructuring. Also this is a kind of standard with [powerplug](https://github.com/renatorib/react-powerplug/blob/master/src/components/Form.js#L16)

**Comment by jedwards1211** [comment]
yes i know, still do you think it's clearer in this library than `watch` or `observe`?

**Comment by TrySound** [comment]
Yep. It's consistency. Observe or watch are not descriptive. Bind I can learn once and use as pattern everywhere.

**Comment by jedwards1211** [comment]
@TrySound `bind` may be more descriptive to you, and more consistent, but I guarantee you if we took a poll of developers they would find observce and watch much more descriptive.

**Comment by TrySound** [comment]
By `descriptive` I mean need to read docs. If you know `bind` pattern across many components you will use it without problems. Something more specific like `observe` is related to concrete component and of course you won't have an idea how to use it.

**Comment by jedwards1211** [comment]
@TrySound well, obviously you're not going to empathize with my point of view at all

**Comment by jedwards1211** [comment]
@TrySound I can understand the desire for consistency but `powerplug` itself isn't consistent, because some of its components pass down functions named `bindFocus` and `bindHover` instead of just `bind`.  So it's clear someone involved with `powerplug` at some point felt that `bind` by itself was a little too vague.  Not to mention that one does `{...bindFocus}` instead of `{...bind(someArgument)}`, that's a potential tripping point.  So is it really a pattern that will save developers confusion compared to `observe`?

**Comment by TrySound** [comment]
@jedwards1211 Powerplug docs are not updated yet.

**Comment by souporserious** [comment]
@jedwards1211 thanks for the suggestions! I totally understand your view, and do like the `watch` terminology. The main reason for `bind` was as @TrySound said, taken from powerplug. I liked the idea that this component could interop with something like powerplug easier, and potentially other libraries that implement the same pattern. This pattern could also allow for additional handlers in the future if needed, but I'm not sure if that's really applicable with react measure. I am open to changing the name if it makes more sense, but I think as @TrySound said, once you learn `bind` you should hopefully be familiar with it. I should also mention this would be fully documented, sorry the above isn't much, I haven't had a chance to do more thorough docs.

**Comment by jedwards1211** [comment]
Okay, well I was making a bigger deal of this than need be, and it sounds like you guys have thought about this carefully.  Thanks!

**Comment by souporserious** [comment]
Thank you! 🙏 I appreciate your insight on everything.

**Comment by souporserious** [comment]
@TrySound pinging you [about this](https://twitter.com/ryanflorence/status/979420610781618176) 😇. Do you think this would be beneficial for the `Viewport` component? From that screenshot, it seems like it could help 🤔.

**Comment by TrySound** [comment]
I don't know. I meant "ping me in PR with your idea" :)
Actually this hook is required for cases like scroll subscribtion. After scroll position is set we probably need additional sizes from the DOM to calculate layout.

**Comment by souporserious** [comment]
Haha oops, yeah I don't have anything right now, we can look at it later and see if it could help. I'll work on getting more of the examples finished in the meantime 😅.

**Comment by jedwards1211** [comment]
@souporserious I've noticed that a lot of the React ecosystem is moving away from HOCs and toward components that take a child function like this.  Apollo GraphQL just made that change.  It's pretty cool to see!  We've known for a long time that this type of API is more convenient than HOCs :smile:

**Comment by souporserious** [comment]
Yup! 😄I'm so happy to see the community move towards them! Especially with the new context API 🎉. When I first saw it introduced in react-motion it changed my life and I wanted everyone to use them everywhere 🔨😆.

**Comment by souporserious** [comment]
@TrySound so it [looks like](https://twitter.com/dan_abramov/status/981865625038573568) `getSnapshotBeforeUpdate` should be used in this library. I'm wondering if there is any use case where you wouldn't want to have measurements before an update 🤔, none I can think of off the top of my head. I'm thinking we could add backwards compatibility for pre-16 apps as well, but not sure if that will add more headache since things _might_ work different.

**Comment by TrySound** [comment]
@souporserious I'm just afraid this might introduce some performance issues. We already have relatively slow polyfill. `getSnapshotBeforeUpdate` here may even more slow down apps.

**Comment by TrySound** [comment]
Also we probably don't need to pull this properties before every render since we already observe their changes.

**Comment by souporserious** [comment]
Ah true. I'll hold off on that then. That reminds me, I think I'd like to add an `observe` prop or something similar to let the user control whether they want to observe changes or they can use the `measure` function to handle measuring whenever necessary.

**Comment by souporserious** [comment]
@TrySound are you familiar with testing? I was thinking about trying out [react-testing-library](react-testing-library) for this library.

**Comment by TrySound** [comment]
@souporserious I don't think it does make sense for this library. You usually need to test browser specific thing which is not related to react. If you want I can push puppeteer environment, however I didn't write tests yet.

**Comment by souporserious** [comment]
The more I've been using `{...bind(id)}`, I'm thinking it should just be `bindRef(id)`. In the beginning I thought it would be nice to interop with libraries like react-powerplug more easily, but with the `composeEvents` function they have now, I think it's just as easy and more clear to do `composeEvents({ ref: bindRef(id) }, bindWhateverElse)` when working with other libraries that need to use `ref`. I also rarely have needed to mix these two and mostly find myself doing things like `innerRef={bind(id).ref}` for libraries that pass the ref through.

Open to any thoughts on this. I'll probably move things over this weekend.

**Comment by jamiewinder** [comment]
Is there a reason for the `{...bind(id)}` syntax rather than simply `ref={bind(id)}`? Is it so you could add other props beyond a ref?

I just tripped up on using this with styled-components because you need to use the `innerRef` prop in that case (i.e. `innerRef={bind(id).ref}`). I find the problem with the spread syntax is that you're not sure what you're spreading. If I were to do `<div ref={this._myRef} {...bind(0)}>` then this isn't going to work, but it won't be immediately obvious why. Forcing the user to assign the `ref` will make it more obvious.

Looking forward to the v3, btw! Is it currently possible to use this in place of AutoSizer in react-window? I've seen the conversation in that repo about doing so, but I don't think it's possible at this stage yet?

**Comment by TrySound** [comment]
They should start using `React.forwardRef` api, so `bind` spread will work well.

**Comment by jedwards1211** [comment]
@jamiewinder yeah if we need to get our own ref to the component, it will be a bit awkward:

```js
<div>
  <input {...bind(id)} ref={c => {
    bind(id).ref(c)
    this.myInput = c
  }} />
</div>
```

The following possibility is less elegant in general, but it would be more elegant in the case that the user needs to pass a `ref` or some other prop that `bind` would currently compete with:

```js
<div>
  {bind(id)(<input ref={c => myInput = c} />)}
</div>
```

**Pull request closed without merging**
